### ISSUE TITLE
Create package on packagist.org

### ISSUE THREAD

**Issue by kentr** [kentr/php-pm-drupal#10]
After #9 is decided & resolved, submit a new package for the repo on [packgist.org](https://packagist.org/packages/submit), and link it to the repo for automatic updates.

Then delete [kentr/php-pm-drupal-adapter](https://packagist.org/packages/kentr/php-pm-drupal-adapter).

**Comment by kentr** [comment]
@marcj You may need to be the one who submits the new package to packgist, so that the package is owned by php-pm.

I'll delete the existing one.

**Comment by marcj** [comment]
Can we rename it to something along the line of other bridges? https://packagist.org/packages/php-pm/, so its called `php-pm/drupal-adapter` in composer

**Comment by kentr** [comment]
I believe `composer.json` is ready now.

**Comment by marcj** [comment]
Added :)

**Comment by kentr** [comment]
I added a repo service hook for the packagist API, with my API key.  On packagist it still says _"This package is not auto-updated"_, but maybe it will engage when the next change is pushed.

If not, it may require the packagist API key of the project's owner.

**Comment by kentr** [comment]
My latest commit went through to packagist automatically, so auto-update appears to be working.
