### ISSUE TITLE
Does this keep Drupal alive between processes ?

### ISSUE THREAD

**Issue by sinasalek** [kentr/php-pm-drupal#13]

**Comment by kentr** [comment]
I'm not sure which processes you mean.  Do you mean between requests?  If so, yes.

It keeps running processes with Drupal in the background, and feeds incoming requests to them.  Incoming requests don't start new processes unless one is killed accidentally.  That's how it speeds up the request cycle, by eliminating a lot of bootstrap overhead.

**Comment by kentr** [comment]
See this post by @marcj for details on the architecture: http://marcjschmidt.de/blog/2014/02/08/php-high-performance.html

**Comment by sinasalek** [comment]
Thanks kentr for the quick reply.
Yes i used reactphp in couple of applications recently and it's great. Also i gave php-pm with your bridge a try. But comparing to a apache+php, it was very slow. so i wondered whether it keeps Drupal alive or not. Now that it does i'm guessing it might have been because of the virtualization layer i used. Have you ran any benchmark for Drupal+ PHP-PM ?

**Comment by kentr** [comment]
I haven’t done any benchmarks yet.  

If you have suggestions on what specifically to benchmark and which benchmarking software to use, I’d like to hear them.

**Comment by sinasalek** [comment]
For HTTP benchmark which is the case here, the easiest tool is Apache bench which is very straight forward to use. Comparing Drupal 8 with and without cashing enable in PHP-PM vs PHP-FPM i think would be a good demonstration.
http://www.sitepoint.com/stress-test-php-app-apachebench/
Here is a good article for benchmarking Drupal using vagrant that covers lot more actually : http://www.jeffgeerling.com/blogs/jeff-geerling/vagrant-vmware-7-vs-virtualbox-5-benchmarks

**Comment by kentr** [comment]
Thx.  Calling this closed.
