### ISSUE TITLE
Allow multiple passes in \Drupal\Core\DrupalKernel::setSitePath()

### ISSUE THREAD

**Issue by kentr** [kentr/php-pm-drupal#2]
The PHP-PM architecture appears to be calling `\Drupal\Core\DrupalKernel::setSitePath()` multiple times. The method has a guard which prevents subsequent calls after the kernel is "booted", which is causing an exception; it needs to allow subsequent calls while still disallowing changes to `sitePath`.

I'm not keen on hacking core, but until a better solution is found I'm proposing patching:

``` php
  public function setSitePath($path) {
    if ($this->booted) {
      throw new \LogicException('Site path cannot be changed after calling boot()');
    }
    $this->sitePath = $path;
  }
```

to:

``` php
  public function setSitePath($path) {
    if ($this->booted && $path !== $this->sitePath) {
      throw new \LogicException('Site path cannot be changed after calling boot()');
    }
    $this->sitePath = $path;
  }
```

**Comment by kentr** [comment]
The patch is in [`kentr-allow-repeated-setSitePath-in-DrupalKernel.patch`](https://github.com/php-pm/php-pm-drupal/blob/master/patches/kentr-allow-repeated-setSitePath-in-DrupalKernel.patch)

**Comment by kentr** [comment]
Resolved with patch mentioned above.

**Comment by kentr** [comment]
Added patch in [Allow repeated calls to DrupalKernel ::setSitePath()](https://www.drupal.org/node/2829346) on d.o

**Comment by andypost** [comment]
https://www.drupal.org/project/drupal/issues/2829346 commited in 8.4.x
